= JEP-0000: BlueOcean Extensibility
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| JEP
| 0000

| Title
| BlueOcean Extensibility

| Sponsor
| http://github.com/imeredith[Ivan Meredith]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Standards

| Created
| 2018-05-15
//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if there will be a BDFL delegate for this JEP.
//| BDFL-Delegate
//| :bulb: Link to github user page :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

BlueOcean extensiblity is the way in which Jenkins plugin developers extend the BlueOcean UI. This JEP describes how extensions are defined, implemented, packaged, and loaded at runtime.    

== Specification

[#extensionfunction]
=== Extension function

Extensions are implemented as functions, pecific extension points will define what contract the extensions must implement. The basic format is

[source,javascript]
----
function(context) {
    // Extension code
}
----
The extension point defines what context it will give extensions. This could be contextual data or it could be callback functions to provide data to the extension point

==== Extensions that render

Extensions that want to render UI are a specialized version of the general extension function. Extension points will pass in a `container` div for the extension to render into.

[source,javascript]
----
function(context) {
    context.container.innerHTML = "<p>No test results</p>"
}
----
=== Extension Store
This is the only global object exposed by the extension system; it stores Extension Points and Extensions implementing it. This is where an extension registry is stored and during javascript execution offers lookup capability to apply the Extension Points or call the rendering function.

==== Registering extensions

Extensions in Jenkins are normally discovered with the `@Extension` annotation. Javascript has no runtime methods to discover extensions automatically, so an explicit call to `register()` is needed.

[source,javascript]
----
window.extensionStore.register(extensionPointId, callbackFn)<1>
----
<1> Parameters
* extensionPointId - Unique string that idenifies the extension point.
* callbackFn - <<extensionfunction>>

==== Listing extensions
[source,javascript]
----
window.extensionStore.getExtensions(extensionPointId)
----

Jenkins relies on reflection to find extensions. This is not possible in Javascript and therefore extensions need to be explicitly registered during the loading of the application. The above example is equivalent to doing the following in Jenkins

[source,java]
----
Jenkins.getExtensionList(<Extension.class>)
----

== Motivation

BlueOcean has an extensibility system built around https://github.com/jenkinsci/js-builder[js-builder] and https://github.com/jenkinsci/js-modules[js-modules]. The issues that this JEP addresses are

* Javascript versioning issues


== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work, e.g. how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.
====

== Backwards Compatibility

[TIP]
====
Describe any incompatibilities and their severity.
Describe how the JEP proposes to deal with these incompatibilities.
If there are no backwards compatibility concerns, this section may simply say:
There are no backwards compatibility concerns related to this proposal.
====

== Security

[TIP]
====
Describe the security impact of this proposal.
Outline what was done to identify and evaluate security issues,
discuss of potential security issues and how they are mitigated or prevented,
and how the JEP interacts with existing permissions, authentication, authorization, etc.
If this proposal will have no impact on security, this section may simply say:
There are no security risks related to this proposal.
====

== Infrastructure Requirements

[TIP]
====
Describing any impact on Jenkins project infrastructure.

Include any additions or changes, interactions with exiting components,
potential instabilities, service-level agreements,
and responsibilities for continuing maintenance.
Explain the scope of infrastructure changes with sufficient detail
to allow initial and on-going cost (in both time and money) to be estimated.
If this proposal will have no impact on infrastructure, this section may simply say:
There are no new infrastructure requirements related to this proposal.
====

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of changes will require human interaction to verify, explain why automated tests are considered impractical.
Then summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Might behavior vary by platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Are any special tools, proprietary software, or online service accounts required to exercise a related code path (Active Directory server, GitHub login, etc.)?
When will testing take place relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

[TIP]
====
Link to any open source reference implementation of code changes for this proposal.
The reference implementation need not be completed before the JEP is <<accepted>>,
but must be completed before any JEP is given "Final" status.
JEPs which will not include code changes may omit this section.
====

== References

[TIP]
====
Provide links to any related documents.
====

[IMPORTANT]
====
When moving this JEP from a Draft to "Accepted" or "Final" state,
include links to the pull requests and mailing list discussions which were involved in the process.
====



